CREATE OR REPLACE FUNCTION isnumeric(text) RETURNS BOOLEAN AS $$
DECLARE x NUMERIC;
BEGIN
    x = $1::NUMERIC;
    RETURN TRUE;
EXCEPTION WHEN others THEN
    RETURN FALSE;
END;
$$
STRICT
LANGUAGE plpgsql IMMUTABLE;

CREATE TABLE PESSOA(
	CPF VARCHAR(11) NOT NULL PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,
	TIPO VARCHAR(15) NOT NULL,
	CONSTRAINT TIPO CHECK (TIPO IN ('funcionario','hospede')),
	CONSTRAINT CPF CHECK ( length(CPF) = 11 AND isnumeric(CPF))
);

CREATE TABLE SERVICOS(
	COD_SERVICO INTEGER NOT NULL PRIMARY KEY,
	PRECO NUMERIC NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	CONSTRAINT PRECO CHECK (PRECO>=0),
	CONSTRAINT COD_SERVICO CHECK (COD_SERVICO>=1)
);

CREATE TABLE FUNCIONARIO(
	CPF VARCHAR(11) NOT NULL,
	COD_SERVICO INTEGER NOT NULL REFERENCES SERVICOS(COD_SERVICO),
	CADASTRADO_POR_CPF VARCHAR(11) REFERENCES FUNCIONARIO(CPF),
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF),
	CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
	CONSTRAINT COD_SERVICO CHECK (COD_SERVICO>=1),
	CONSTRAINT CPF CHECK ( length(CPF) = 11 AND isnumeric(CPF)),
	CONSTRAINT CADASTRADO_POR_CPF CHECK ( length(CADASTRADO_POR_CPF) = 11 AND isnumeric(CADASTRADO_POR_CPF))
);

CREATE TABLE QUARTO(
	NUM_QUARTO INTEGER NOT NULL PRIMARY KEY,
	TIPO VARCHAR(10) NOT NULL,
	OCUPADO BOOLEAN NOT NULL,
	CAPACIDADE INTEGER NOT NULL,
	CUSTO_ADICIONAL NUMERIC NOT NULL,
	CONSTRAINT NUM_QUARTO CHECK (NUM_QUARTO>0),
	CONSTRAINT TIPO CHECK (TIPO IN ('dormitorio','standard','master')),
	CONSTRAINT CAPACIDADE CHECK (CAPACIDADE>0),
	CONSTRAINT CUSTO_ADICIONAL CHECK (CUSTO_ADICIONAL>=0)
);

CREATE TABLE FICHA(
	COD_FICHA INTEGER NOT NULL PRIMARY KEY,
	CPF_FUNC VARCHAR(11) NOT NULL REFERENCES FUNCIONARIO(CPF),
	NUM_QUARTO INTEGER NOT NULL REFERENCES QUARTO(NUM_QUARTO),
	CUSTO_BASE NUMERIC NOT NULL,
	QTD_HOSPEDES INTEGER NOT NULL,
	CHECK_IN TIMESTAMP NOT NULL,
	CHECK_OUT TIMESTAMP NOT NULL,
	CONSTRAINT COD_FICHA CHECK (COD_FICHA>=1),
	CONSTRAINT CPF_FUNC CHECK ( length(CPF_FUNC) = 11 AND isnumeric(CPF_FUNC)),
	CONSTRAINT NUM_QUARTO CHECK (NUM_QUARTO>=0),
	CONSTRAINT CUSTO_BASE CHECK (CUSTO_BASE>=0),
	CONSTRAINT QTD_HOSPEDES CHECK (QTD_HOSPEDES>=1)
);

CREATE TABLE HOSPEDE(
	CPF VARCHAR(11) NOT NULL,
	ENDERECO VARCHAR(40) NOT NULL,
	CONSTRAINT PK_HOSPEDE PRIMARY KEY (CPF),
	CONSTRAINT FK_HOSPEDE_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
	CONSTRAINT CPF CHECK ( length(CPF) = 11 AND isnumeric(CPF))
);

CREATE TABLE POSSUI(
	CPF VARCHAR(11) NOT NULL,
	COD_FICHA INTEGER NOT NULL,
	CONSTRAINT PK_POSSUI PRIMARY KEY (CPF, COD_FICHA),
	CONSTRAINT FK_POSSUI_HOSPEDE FOREIGN KEY (CPF) REFERENCES HOSPEDE(CPF),
	CONSTRAINT FK_POSSUI_FICHA FOREIGN KEY (COD_FICHA) REFERENCES FICHA(COD_FICHA),
	CONSTRAINT CPF CHECK ( length(CPF) = 11 AND isnumeric(CPF)),
	CONSTRAINT COD_FICHA CHECK (COD_FICHA>=1)
);

CREATE TABLE TELEFONE(
	CPF VARCHAR(11) NOT NULL,
	NUM_TELEFONE VARCHAR(9) NOT NULL,
	CONSTRAINT PK_TELEFONE PRIMARY KEY (CPF,NUM_TELEFONE),
	CONSTRAINT FK_TELEFONE_HOSPEDE FOREIGN KEY (CPF) REFERENCES HOSPEDE(CPF),
	CONSTRAINT CPF CHECK ( length(CPF) = 11 AND isnumeric(CPF)),
	CONSTRAINT NUM_TELEFONE CHECK ( length(NUM_TELEFONE) = 9 AND isnumeric(NUM_TELEFONE))
);

CREATE TABLE OFERECE(
	NUM_QUARTO INTEGER NOT NULL,
	COD_SERVICO INTEGER NOT NULL,
	DATA_EVENTO TIMESTAMP NOT NULL,
	CONSTRAINT PK_OFERECE PRIMARY KEY (NUM_QUARTO,COD_SERVICO,DATA_EVENTO),
	CONSTRAINT FK_OFERECE_QUARTO FOREIGN KEY (NUM_QUARTO) REFERENCES QUARTO(NUM_QUARTO),
	CONSTRAINT FK_OFERECE_SERVICOS FOREIGN KEY (COD_SERVICO) REFERENCES SERVICOS(COD_SERVICO),
	CONSTRAINT NUM_QUARTO CHECK (NUM_QUARTO>=0),
	CONSTRAINT COD_SERVICO CHECK (COD_SERVICO>=1)
);
