CREATE TABLE PESSOA(
	CPF VARCHAR(11) NOT NULL PRIMARY KEY, -- DEVE SER DIGITOS
	NOME VARCHAR(30) NOT NULL,
	TIPO VARCHAR(15) NOT NULL
);

CREATE TABLE FUNCIONARIO(
	CPF VARCHAR(11) NOT NULL,
	COD_SERVIÇO Integer NOT NULL REFERENCES SERVIÇOS(COD_SERVIÇO),
	CADASTRADO_POR_CPF VARCHAR(11) REFERENCES FUNCIONARIO(CPF),
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF),
	CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
	--CONSTRAINT CK_QTD_ESTOQUE_LOJA CHECK (QTDESTOCADALOJA >=0 AND QTDESTOCADALOJA<=999)
);

CREATE TABLE HOSPEDE(
	CPF VARCHAR(11) NOT NULL,
	COD_FICHA Integer NOT NULL REFERENCES FICHA(COD_FICHA),
	ENDEREÇO VARCHAR(40) NOT NULL,
	CONSTRAINT PK_HOSPEDE PRIMARY KEY (CPF),
	CONSTRAINT FK_HOSPEDE_PESSOA FOREIGN KEY (CPF) REFERENCES PESSOA(CPF)
);

CREATE TABLE FICHA(
	COD_FICHA INTEGER NOT NULL PRIMARY KEY,
	CPF_FUNC VARCHAR(11) NOT NULL REFERENCES FUNCIONARIO(CPF),
	NUM_QUARTO INTEGER NOT NULL REFERENCES QUARTO(NUM_QUARTO),
	CUSTO_BASE NUMERIC NOT NULL,
	QTD_HOSPEDES INTEGER NOT NULL,
	CHECK_IN TIMESTAMP NOT NULL,
	CHECK_OUT TIMESTAMP NOT NULL
);

CREATE TABLE QUARTO(
	NUM_QUARTO INTEGER NOT NULL PRIMARY KEY,
	TIPO VARCHAR(10) NOT NULL,
	-- OCUPADO? BOOLEAN?
	CAPACIDADE INTEGER NOT NULL,
	CUSTO_ADICIONAL NUMERIC NOT NULL
);

CREATE TABLE SERVIÇOS(
	COD_SERVIÇO INTEGER NOT NULL PRIMARY KEY,
	PREÇO NUMERIC NOT NULL,
	DESCRIÇÃO VARCHAR(50) NOT NULL
);

CREATE TABLE OFERECE(
	NUM_QUARTO INTEGER NOT NULL,
	COD_SERVIÇO INTEGER NOT NULL,
	DATA_EVENTO TIMESTAMP NOT NULL,
	CONSTRAIN PK_OFERECE PRIMARY KEY (NUM_QUARTO,COD_SERVIÇO,DATA_EVENTO),
	CONSTRAIN FK_OFERECE_QUARTO FOREIGN KEY (NUM_QUARTO) REFERENCES QUARTO(NUM_QUARTO),
	CONSTRAIN FK_OFERECE_SERVIÇOS FOREIGN KEY (COD_SERVIÇO) REFERENCES SERVIÇOS(COD_SERVIÇO)
);

CREATE TABLE TELEFONE(
	CPF VARCHAR(11) NOT NULL,
	NUM_TELEFONE VARCHAR(9) NOT NULL,
	CONSTRAIN PK_TELEFONE PRIMARY KEY (CPF,TELEFONE),
	CONSTRAIN FK_TELEFONE_HOSPEDE FOREIGN KEY (CPF) REFERENCES HOSPEDE(CPF)
);
