CREATE SCHEMA BANCO;

CREATE TABLE CONTA
(
	NUMERO INTEGER NOT NULL PRIMARY KEY,
	SENHA INTEGER NOT NULL,
	TIPO VARCHAR(30) NOT NULL,
	DINHEIRO NUMERIC(2) NOT NULL,
	CPF_PROPRIETARIO VARCHAR(11),

	CONSTRAIN TIPO CHECK (TIPO IN ('POUPANCA','CORRENTE'))
	CONSTRAINT CPF_PROPRIETARIO CHECK ( length(CPF) = 11 AND isnumeric(CPF))
)

CREATE TABLE FUNCIONARIO
(
	CPF VARCHAR(11) NOT NULL PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,

	CONSTRAINT CPF_PROPRIETARIO CHECK ( length(CPF) = 11 AND isnumeric(CPF))
)

CREATE TABLE USUARIO
(
	CPF VARCHAR(11) NOT NULL PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL,

	CONSTRAINT CPF_PROPRIETARIO CHECK ( length(CPF) = 11 AND isnumeric(CPF))
)
