CREATE TABLE SITE(
   ID_SITE INTEGER NOT NULL,
   NOME VARCHAR(50) NOT NULL,
   SITE VARCHAR(50) NOT NULL,

   CONSTRAINT PK_SITE PRIMARY KEY (ID_SITE)
);

CREATE TABLE ESTADO(
   UF INTEGER NOT NULL,
   NOME VARCHAR(50) NOT NULL,

   CONSTRAINT PK_ESTADO PRIMARY KEY (UF)
);

CREATE TABLE CIDADE(
   ID_CIDADE INTEGER NOT NULL,
   NOME VARCHAR(50) NOT NULL,
   UF INTEGER NOT NULL,

   CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE),
   CONSTRAINT FK_HOTEL_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES HOTEL(ID_HOTEL)
);

CREATE TABLE HOTEL(
   ID_HOTEL INTEGER NOT NULL,
   NOME VARCHAR(50) NOT NULL,
   DESCRICAO VARCHAR(200) NOT NULL,
   DIS_PRAIA INTEGER NOT NULL,
   PISCINA BOOL NOT NULL,
   ID_CIDADE INTEGER NOT NULL,

   CONSTRAINT PK_HOTEL PRIMARY KEY (ID_HOTEL),
   CONSTRAINT FK_HOTEL_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES HOTEL(ID_HOTEL)
);


CREATE TABLE AVALIACAO(
   ID_AVALIACAO INTEGER NOT NULL,
   AVALIACAO VARCHAR(200) NOT NULL,
   ID_HOTEL INTEGER NOT NULL,

   CONSTRAINT PK_AVALIACAO PRIMARY KEY (ID_AVALIACAO),
   CONSTRAINT FK_AVALIACAO_HOTEL FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL)
);

CREATE TABLE OFERTA(
    ID_HOTEL INTEGER NOT NULL,
    ID_SITE INTEGER NOT NULL,
    DATA_START TIMESTAMP NOT NULL,
    DATA_END TIMESTAMP NOT NULL,
    CAPACIDADE_QUARTO INTEGER NOT NULL,
    WIFI BOOLEAN NOT NULL,
    AR_CONDICIONADO BOOLEAN NOT NULL,
    CAFE BOOLEAN NOT NULL,
    PRECO NUMERIC NOT NULL,

    CONSTRAINT PK_OFERTA PRIMARY KEY (ID_HOTEL,ID_SITE),
    CONSTRAINT FK_OFERTA_HOTEL FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL),
    CONSTRAINT FK_OFERTA_SITE FOREIGN KEY (ID_SITE) REFERENCES SITE(ID_SITE),

    CONSTRAINT ID_HOTEL CHECK (ID_HOTEL>=0),
    CONSTRAINT ID_SITE CHECK (ID_SITE>=0),
    CONSTRAINT CAPACIDADE_QUARTO CHECK (CAPACIDADE_QUARTO>0),
    CONSTRAINT PRECO CHECK (PRECO>=0)
);

CREATE TABLE RESERVA
(
    ID INTEGER NOT NULL,
    ID_HOTEL INTEGER NOT NULL,
    ID_SITE INTEGER NOT NULL,
    CPF INTEGER NOT NULL,
    NOME_CLIENTE VARCHAR(50) NOT NULL,
    ADULTOS INTEGER NOT NULL,
    CRIANCAS INTEGER NOT NULL,
    RESERVA_START TIMESTAMP NOT NULL,
    RESERVA_END TIMESTAMP NOT NULL,

    CONSTRAINT PK_RESERVA PRIMARY KEY(ID),
    CONSTRAINT FK_RESERVA_OFERTA FOREIGN KEY (ID_HOTEL,ID_SITE) REFERENCES OFERTA(ID_HOTEL,ID_SITE),

    CONSTRAINT ID CHECK (ID>=0),
    CONSTRAINT ID_HOTEL CHECK (ID_HOTEL>=0),
    CONSTRAINT ID_SITE CHECK (ID_SITE>=0),
    CONSTRAINT ADULTOS CHECK (ADULTOS>0),
    CONSTRAINT CRIANCAS CHECK (CRIANCAS>0)
);
